#!/usr/bin/env python3
"""update_scenarios.py — 场景资产合并器(实施 T1 · 对抗式审查矛盾 2 修正)

替代 .notes/_gen_scenarios.py 一次性脚本,成为 references/scenarios.yaml 的
正式维护通道。

语义:
  读 scenarios/*.yaml 域片段 → 校验字段契约(§07 §2.2) → 按 scenario_id 合并进
  references/scenarios.yaml(命中 = 覆盖更新 / 未命中 = 追加末尾) → 幂等写回。

幂等保证:
  同一输入连跑两次,第二次输出与第一次 byte-identical(覆盖更新为同值写入)。

用法:
  python scripts/update_scenarios.py [--scenes-dir scenarios]
                                      [--scenarios references/scenarios.yaml]
                                      [--only 文件名.yaml] [--dry-run]

字段契约(§07 §2.2): wake_word / scenario_id / scenario_title / dimensions / prompt / status / result
status 二态: '' (可用) / 【待开发】(不可执行但仍展示)
"""
import argparse
import sys
from pathlib import Path

import yaml

SKILL_DIR = Path(__file__).resolve().parent.parent
DEFAULT_SCENES_DIR = SKILL_DIR / "scenarios"
DEFAULT_SCENARIOS = SKILL_DIR / "references" / "scenarios.yaml"

REQUIRED_FIELDS = {
    "wake_word", "scenario_id", "scenario_title",
    "dimensions", "prompt", "status", "result",
}
VALID_STATUS = {"", "【待开发】"}

HEADER_LINES = [
    "# 作息管家 · 场景资产(§07 契约)",
    "# 唯一事实源 — 所有 HELP HTML / 人类视图 / 机读视图都从这里派生",
    "# 字段契约(§07 §2.2): wake_word / scenario_id / scenario_title / dimensions / prompt / status / result",
    "# status 二态: '' (可用) / 【待开发】(不可执行但仍展示)",
    "",
    "# Generated by scripts/update_scenarios.py — 场景合并器(幂等)",
]


def load_yaml(path: Path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f) or []


def validate_fragment(entries, frag_name: str) -> list[str]:
    """校验片段字段契约,返回错误列表(空 = 通过)。"""
    errors = []
    seen_ids = set()
    for i, e in enumerate(entries):
        if not isinstance(e, dict):
            errors.append(f"{frag_name}[{i}]: 场景条目必须是映射,实际 {type(e).__name__}")
            continue
        missing = REQUIRED_FIELDS - set(e)
        if missing:
            errors.append(f"{frag_name}[{i}] {e.get('scenario_id', '?')}: 缺字段 {sorted(missing)}")
        sid = e.get("scenario_id")
        if not sid:
            errors.append(f"{frag_name}[{i}]: scenario_id 必填且非空")
        elif sid in seen_ids:
            errors.append(f"{frag_name}[{i}]: scenario_id 在片段内重复: {sid}")
        seen_ids.add(sid)
        if e.get("status") not in VALID_STATUS:
            errors.append(f"{frag_name}[{i}] {sid}: status 非法 {e.get('status')!r}(仅 '' / 【待开发】)")
    return errors


def merge_fragment(scenarios, entries):
    """按 scenario_id 合并:命中覆盖(原位保序)/ 未命中追加末尾。返回 (updated, added)。"""
    by_id = {s["scenario_id"]: s for s in scenarios}
    updated, added = [], []
    for e in entries:
        sid = e["scenario_id"]
        if sid in by_id:
            by_id[sid].update(e)
            updated.append(sid)
        else:
            scenarios.append(e)
            by_id[sid] = e
            added.append(sid)
    return updated, added


def dump_scenarios(scenarios, path: Path) -> None:
    lines = list(HEADER_LINES)
    lines.append(f"# 场景总数: {len(scenarios)}")
    lines.append("")
    body = yaml.safe_dump(scenarios, allow_unicode=True, sort_keys=False,
                          default_flow_style=False)
    path.write_text("\n".join(lines) + body, encoding="utf-8")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="域场景片段合并进 references/scenarios.yaml")
    ap.add_argument("--scenes-dir", default=str(DEFAULT_SCENES_DIR))
    ap.add_argument("--scenarios", default=str(DEFAULT_SCENARIOS))
    ap.add_argument("--only", default=None, help="只合并指定文件名(如 record.yaml);默认合并全部")
    ap.add_argument("--dry-run", action="store_true", help="只报告不写盘")
    args = ap.parse_args(argv)

    scenes_dir = Path(args.scenes_dir)
    scenarios_path = Path(args.scenarios)
    fragments = sorted(scenes_dir.glob("*.yaml")) if scenes_dir.exists() else []
    if args.only:
        fragments = [p for p in fragments if p.name == args.only]
    if not fragments:
        print(f"✗ 无场景片段:{scenes_dir}/ (目录不存在或无 *.yaml)")
        return 1

    # 1) 全量校验(任何片段非法 → 不写盘)
    errors = []
    for p in fragments:
        entries = load_yaml(p)
        if not isinstance(entries, list):
            errors.append(f"{p.name}: 顶层必须是场景列表(7 字段契约),实际 {type(entries).__name__}")
            continue
        errors += validate_fragment(entries, p.name)
    if errors:
        for e in errors:
            print(f"✗ {e}", file=sys.stderr)
        print(f"✗ 校验失败 {len(errors)} 处,未写盘。", file=sys.stderr)
        return 1

    # 2) 读总账(不存在则从零开始)
    scenarios = load_yaml(scenarios_path) if scenarios_path.exists() else []
    if not isinstance(scenarios, list):
        print(f"✗ 总账 {scenarios_path} 顶层必须是场景列表", file=sys.stderr)
        return 1

    # 3) 合并
    total_updated, total_added = [], []
    for p in fragments:
        entries = load_yaml(p)
        updated, added = merge_fragment(scenarios, entries)
        print(f"• {p.name}: 更新 {len(updated)} / 新增 {len(added)}")
        total_updated += updated
        total_added += added
    print(f"合计:更新 {len(total_updated)} / 新增 {len(total_added)} / 总场景 {len(scenarios)}")

    # 4) 写回
    if not args.dry_run and (total_updated or total_added):
        dump_scenarios(scenarios, scenarios_path)
        print(f"✓ 已写回 {scenarios_path}")
    elif args.dry_run:
        print("(dry-run 未写盘)")
    else:
        print("(无变化,未写盘)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
